name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: Install dependencies
      working-directory: l-lang/src
      run: dotnet restore

    - name: Build
      working-directory: l-lang/src
      run: dotnet build --configuration Release --no-restore

    - name: Test
      working-directory: l-lang/src
      run: dotnet test --no-restore --verbosity normal -p:CollectCoverage=true -p:CoverletOutputFormat=opencover -p:CoverletOutput=./TestResults/LLang.Tests.opencover.xml

    - name: Upload Coverage
      uses: actions/upload-artifact@v1
      with:
        name: LLang.Tests.opencover.xml
        path: l-lang/src/LLang.Tests/TestResults/LLang.Tests.opencover.xml
